### ISSUE TITLE
매니저 컨트롤러 테스트 코드 작성

### ISSUE THREAD

**Issue by seasameoil** [Team-JubJub/ZupZup-Web_backend#10]
## 💬 Description
매니저 컨트롤러 관련 테스트 코드 작성

## 📝 Todo
- [x] 매니저 CRUD 컨트롤러 테스트 작성
- [x] 매니저 로그인 컨트롤러 테스트
- [x] rest Docs 설정
