### ISSUE TITLE
[REFACTOR] 인증 기능 추가

### ISSUE THREAD

**Issue by seasameoil** [Team-JubJub/ZupZup-Web_backend#97]
## 💬 Description
인증 기능 구현을 위한 모듈 추가 및 수정

## 📝 Todo
- [ ] spring-module-auth 추가
- [ ] 자체 로그인 기능 추가
  - [ ] ManagerAuthority, MemberAuthority 도메인 삭제
  - [ ] 관련 기능 수정
